language: php
cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 5.3
  - 5.4
  - 5.6
  - 7.0
env:
  - VERSION=8.x-1.x

sudo: false

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # MySQL Config.
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP Config.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build Drupal test.
  - composer global require phing/phing
  - phing build -Dversion=$VERSION -Dbranch=$TRAVIS_COMMIT

  # Install Drupal test.
  - phing install -Ddb.database=drupal
  - if [ $VERSION != "HEAD" ]; then phing update; fi

before_script:
  - cd docroot
  - drush rs 8080 &>/dev/null &
  - phantomjs --webdriver=4444 > /dev/null &
  - sleep 5

script:
  - cd ..
  - behat --strict

matrix:
  fast_finish: true
